$('.logo-slider').owlCarousel({
    autoplay:true,
    autoplayTimeout:1750,
    loop:true,
    margin:10,
    responsive:{
        0:{
            items:2
        },
        600:{
            items:3
        },
        1000:{
            items:6
        },
        1500:{
            items:8
        }
    }
})
